import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomSeed } from '../../helpers/random.js';
import { buildAutomationPlan, type AutomationAction, type AutomationPlan, type TestCaseForPlanning, type ValueSource } from './plan.js';

const projectRoot = process.cwd();
export type AutomationMode = 'hybrid' | 'deterministic' | 'codex';
export interface AutomationAgentOptions { testDesignPath: string; outputPath: string; testFilePath: string; featureId?: string; mode?: AutomationMode; }
interface TestDesignContract { feature: string; test_cases: TestCaseForPlanning[]; }
export interface AutomationResult { schema_version: string; feature: string; classification?: { functional_area: string; related_areas: string[]; suites: string[]; tags: string[] }; automation_mode?: AutomationMode; codex_invoked?: boolean; codex_reason?: string; random_seed?: string; test_cases: { test_case_id: string; automation_status: 'automated' | 'not_automated'; test_file: string | null; plan?: AutomationPlan; reason?: string; unsupported_step?: number; unsupported_operation?: string; generation?: { mode: 'deterministic' | 'codex_fallback' | 'codex' }; fallback?: { invoked: boolean; reason_code: string; unsupported_step?: number; unsupported_operation?: string; resolved: boolean } }[]; summary: { total: number; automated: number; not_automated: number; automation_coverage?: number }; }

/** Central registry: semantic UI capabilities resolve to existing POM/fixture APIs. */
export const capabilityRegistry: Record<string, string> = {
  'click:navigation.menu': 'authenticatedInventoryPage.openMenu()', 'click:navigation.logout': 'authenticatedInventoryPage.logout()', 'click:inventory.cart': 'authenticatedInventoryPage.openCart()', 'click:cart.continue': 'cartPage.continueShopping()', 'click:cart.checkout': 'cartPage.startCheckout()', 'click:checkout.continue': 'checkoutPage.continue()', 'click:checkout.finish': 'checkoutPage.finish()',
  'select:inventory.sort': 'authenticatedInventoryPage.sortBy',
  'read_collection:inventory.product_names': 'authenticatedInventoryPage.getProductNames()', 'read_collection:inventory.product_prices': 'authenticatedInventoryPage.getProductPrices()',
  'assert_collection_ascending:string': 'sortStringsAscending', 'assert_collection_descending:string': 'sortStringsDescending', 'assert_collection_ascending:number': 'sortNumbersAscending', 'assert_collection_descending:number': 'sortNumbersDescending',
  'assert_visible:inventory.heading': "await expect(page.getByText('Products', { exact: true })).toBeVisible()", 'assert_visible:login.form': "await expect(page.getByPlaceholder('Username')).toBeVisible()", 'assert_visible:navigation.logout': "await expect(page.getByRole('link', { name: 'Logout' })).toBeVisible()", 'assert_visible:cart.heading': 'await cartPage.waitUntilLoaded()', 'assert_visible:checkout.summary': "await expect(page).toHaveURL(/checkout-step-two\\.html$/)", 'assert_url:inventory.url': "await expect(page).toHaveURL(/\\/inventory\\.html$/)", 'assert_url:login.home': "await expect(page).toHaveURL(/\\/$/)",
};
export function classifyFeature(feature: string, plans: AutomationPlan[]): AutomationResult['classification'] {
  const text = `${feature} ${plans.flatMap((p) => p.actions.map((a) => 'target' in a ? a.target : '')).join(' ')}`.toLowerCase();
  const area = /checkout/.test(text) ? 'checkout' : /sorting|sort/.test(text) ? 'sorting' : /product.*detail|detail/.test(text) ? 'product-details' : /cart/.test(text) ? 'cart' : /login|auth/.test(text) ? 'login' : /inventory/.test(text) ? 'inventory' : feature;
  const related = [...new Set((/checkout/.test(text) ? ['inventory', 'cart'] : []).filter((x) => x !== area))];
  const suites = area === 'login' ? ['smoke', 'regression'] : ['regression'];
  return { functional_area: area, related_areas: related, suites, tags: [`@${area}`, ...suites.map((s) => `@${s}`)] };
}
function loadTestDesign(path: string): TestDesignContract { if (!existsSync(path)) throw new Error(`Test Design contract does not exist: ${path}`); return JSON.parse(readFileSync(path, 'utf8')) as TestDesignContract; }
function sourceExpression(source: ValueSource | string | number): string { if (typeof source === 'string' || typeof source === 'number') return JSON.stringify(source); if (source.type === 'runtime') return source.key; if (source.type === 'environment') return 'credentials'; if (source.type === 'test_data') return source.key === 'checkoutCustomer' ? 'customer' : `getTestData('${source.key}')`; return JSON.stringify(source.value); }
function renderAction(action: AutomationAction): string {
  const key = `${action.type}:${'target' in action ? action.target : ''}`;
  if (action.type === 'navigate') return 'await loginPage.navigate();';
  if (action.type === 'click') return action.target === 'inventory.add_product' ? `await authenticatedInventoryPage.addProductByName(${sourceExpression(action.value_source!)});` : `await ${capabilityRegistry[key]};`;
  if (action.type === 'fill_form') return action.target === 'login.credentials' ? 'await loginPage.login(credentials.username, credentials.password);' : 'await checkoutPage.fillInformation(customer.firstName, customer.lastName, customer.postalCode);';
  if (action.type === 'select') return `await ${capabilityRegistry[key]}(${sourceExpression(action.value_source)});`;
  if (action.type === 'read') return `const ${action.save_as} = ${action.target === 'inventory.product_name' ? `await authenticatedInventoryPage.getProductName(${action.index ?? 0})` : action.target === 'cart.product_names' ? 'await cartPage.getProductNames()' : 'await checkoutPage.getProductNames()'};`;
  if (action.type === 'read_collection') return `const ${action.save_as} = (await ${capabilityRegistry[key]})${action.value_type === 'number' ? '.map(normalizeNumericText)' : ''};`;
  if (action.type === 'select_random_items') return `const ${action.save_as} = await authenticatedInventoryPage.selectRandomProducts(${action.count});\n  const selectedProductNames = ${action.save_as}.map((product) => product.name);`;
  if (action.type === 'add_items') return `await authenticatedInventoryPage.addProductsToCart(${sourceExpression(action.value_source)});`;
  if (action.type === 'read_badge') return `const ${action.save_as} = await authenticatedInventoryPage.cartBadgeCount();`;
  if (action.type === 'assert_visible' || action.type === 'assert_hidden' || action.type === 'assert_url') return capabilityRegistry[key] ?? `throw new Error(${JSON.stringify(`Unsupported capability ${key}`)});`;
  if (action.type === 'assert_text') return `await expect(await checkoutPage.getConfirmationMessage()).toBe(${sourceExpression(action.expected as ValueSource)});`;
  if (action.type === 'assert_contains') return `await expect(${action.actual_from}).toEqual(expect.arrayContaining([${sourceExpression(action.expected as ValueSource)}]));`;
  if (action.type === 'assert_array_equal') return `await expect(${action.actual_from}).toEqual(${sourceExpression(action.expected as ValueSource)});`;
  if (action.type === 'assert_equals') return `await expect(${action.actual_from}).toBe(${sourceExpression(action.expected as ValueSource)});`;
  if (action.type === 'assert_collection_ascending' || action.type === 'assert_collection_descending') { const valueType = action.value_type === 'number' ? 'number' : 'string'; const fn = capabilityRegistry[`${action.type}:${valueType}`]; return `await expect(${action.actual_from}).toEqual(${fn}(${action.actual_from}));`; }
  if (action.type === 'reuse') return `const ${action.target} = ${sourceExpression(action.value_source)};`;
  throw new Error(`Unsupported plan action: ${JSON.stringify(action)}`);
}
function importsFor(plan: AutomationPlan): string { const imports = ["import { expect, test } from '../fixtures/test.fixture.js';"]; if (plan.actions.some((a) => a.type.startsWith('assert_collection'))) imports.push("import { normalizeNumericText, sortNumbersAscending, sortNumbersDescending, sortStringsAscending, sortStringsDescending } from '../helpers/sorting.js';"); if (plan.actions.some((a) => a.type === 'fill_form' && a.target === 'checkout.customer_information')) imports.push("import { createCheckoutCustomer } from '../helpers/test-data.js';"); return imports.join('\n'); }
function renderPlan(testCase: TestCaseForPlanning, plan: AutomationPlan, tags: string[]): string { const needsCustomer = plan.actions.some((a) => a.type === 'fill_form' && a.target === 'checkout.customer_information'); return `test(${JSON.stringify(`${tags.join(' ')} ${testCase.id}: ${testCase.title}`)}, async ({ page, loginPage, credentials, authenticatedInventoryPage, cartPage, checkoutPage }) => {\n  ${needsCustomer ? 'const customer = createCheckoutCustomer();' : ''}\n  ${plan.actions.map(renderAction).join('\n  ')}\n});`; }
export function runAutomationAgent(options: AutomationAgentOptions): AutomationResult { const design = loadTestDesign(resolve(projectRoot, options.testDesignPath)); const results: AutomationResult['test_cases'] = []; const plans: AutomationPlan[] = []; for (const testCase of design.test_cases) { const planned = buildAutomationPlan(testCase); if ('unsupported_step' in planned) results.push({ test_case_id: testCase.id, automation_status: 'not_automated', test_file: null, unsupported_step: planned.unsupported_step, unsupported_operation: planned.unsupported_operation, reason: planned.reason }); else { plans.push(planned); results.push({ test_case_id: testCase.id, automation_status: 'automated', test_file: options.testFilePath, plan: planned }); } } const automated = results.filter((r) => r.automation_status === 'automated').length; const classification = classifyFeature(options.featureId ?? design.feature, plans); if (automated > 0) { const file = resolve(projectRoot, options.testFilePath); mkdirSync(resolve(file, '..'), { recursive: true }); const tags = classification?.tags ?? []; writeFileSync(file, `${importsFor(plans[0])}\n\n${design.test_cases.filter((_, i) => results[i].automation_status === 'automated').map((tc, i) => renderPlan(tc, plans[i], tags)).join('\n\n')}\n`, 'utf8'); } const result: AutomationResult = { schema_version: '1.1', feature: design.feature, classification, automation_mode: options.mode ?? 'deterministic', codex_invoked: false, random_seed: randomSeed(), test_cases: results, summary: { total: results.length, automated, not_automated: results.length - automated, automation_coverage: results.length ? automated / results.length : 0 } }; const output = resolve(projectRoot, options.outputPath); mkdirSync(resolve(output, '..'), { recursive: true }); writeFileSync(output, `${JSON.stringify(result, null, 2)}\n`, 'utf8'); return result; }
function argumentValue(args: string[], name: string): string { const index = args.indexOf(name); const value = index >= 0 ? args[index + 1] : undefined; if (!value || value.startsWith('--')) throw new Error('Usage: npx tsx agents/automation/index.ts --test-design <path> --output <path> --test-file <path>'); return value; }
if (process.argv.includes('--test-design')) { const args = process.argv.slice(2); const result = runAutomationAgent({ testDesignPath: argumentValue(args, '--test-design'), outputPath: argumentValue(args, '--output'), testFilePath: argumentValue(args, '--test-file') }); console.log(`Automation Agent completed. Automated: ${result.summary.automated}; Not automated: ${result.summary.not_automated}`); }
