import { chromium, type Page } from '@playwright/test';
import { existsSync, mkdirSync, readdirSync, unlinkSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

export type FindingType = 'observation' | 'defect' | 'risk' | 'unknown_resolved' | 'unexpected_behavior';
export type SemanticActionType = 'authenticate' | 'observe_collection' | 'select_visible_item' | 'capture_value' | 'navigate_via_ui' | 'inspect_state' | 'compare_values' | 'go_back' | 'capture_evidence' | 'add_selected_items' | 'open_cart' | 'remove_item' | 'capture_collection';
export interface ExplorationPlanAction { type: SemanticActionType; target?: string; save_as?: string; scope_item?: string; reason: string; }
export interface ExplorationPlan { charter_id: string; focus: string; source_ids: string[]; actions: ExplorationPlanAction[]; }
export interface ExploratoryFinding { id: string; feature: string; charter: string; type: FindingType; title: string; description: string; status: 'observation' | 'potential_defect' | 'confirmed_defect' | 'not_a_defect' | 'needs_investigation'; steps_to_reproduce: string[]; expected: string; actual: string; expected_or_reference: string; observed_behavior: string; risk: string; severity?: 'critical' | 'high' | 'medium' | 'low' | 'unknown'; evidence: string[]; timestamp: string; unknown_id?: string; traceability?: { scenario_ids: string[]; risk_ids: string[]; unknown_ids: string[]; scope_items: string[] }; }
export interface CoverageItem { scope_item: string; status: 'covered' | 'blocked' | 'unexplored'; reason?: string; }
export interface ExplorationResult { exploratory_status: 'executed' | 'executed_with_gaps' | 'failed'; feature: string; feature_path: string; discovery_path: string; charters: Charter[]; plans: ExplorationPlan[]; charters_planned: number; charters_executed: number; charters_blocked: number; findings_generated: number; actions: string[]; evidence: string[]; runtime_values: Record<string, string>; unknowns: Array<{ id: string; status: 'resolved' | 'unresolved'; observation_id?: string }>; coverage: { scope_items_explored: number; scope_items_unexplored: number; items: CoverageItem[] }; started_at: string; completed_at: string; error?: string; }
interface Charter { id: string; mission: string; focus: string[]; risks: string[]; unknowns: string[]; }

const root = process.cwd();
const quote = (value: string): string => value.replace(/^['"]|['"]$/g, '').trim();
const unaccent = (value: string): string => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const has = (text: string, pattern: RegExp): boolean => pattern.test(unaccent(text));
const yamlValue = (source: string, key: string): string => source.match(new RegExp(`^\\s*${key}:\\s*[>]?\\s*(.+)$`, 'mi'))?.[1]?.trim().replace(/^['"]|['"]$/g, '') ?? '';

function listAfter(source: string, heading: string): string[] {
  const lines = source.replace(/\r/g, '').split('\n'); const start = lines.findIndex((line) => new RegExp(`^\\s*${heading}:`).test(line)); if (start < 0) return [];
  const baseIndent = lines[start].search(/\S|$/); const values: string[] = [];
  for (const line of lines.slice(start + 1)) { const indent = line.search(/\S|$/); if (line.trim() && indent <= baseIndent) break; const item = line.match(/^\s+-\s+(?:id:\s*)?(.+)$/); if (item) values.push(quote(item[1])); }
  return values;
}
function ids(discovery: string, prefix: string): string[] { return [...discovery.matchAll(new RegExp(`\\b${prefix}-[A-Z0-9-]+\\b`, 'g'))].map((match) => match[0]).filter((id, index, all) => all.indexOf(id) === index); }
function chartersFrom(discovery: string): Charter[] {
  const block = discovery.split('exploratory_charters:\n')[1]?.split('\nrequirements:')[0] ?? ''; const risks = ids(discovery, 'RSK'); const unknowns = ids(discovery, 'UNK');
  return block.split(/\n(?=  - id:)/).filter(Boolean).map((item) => ({ id: quote(item.match(/^  - id:\s*(.+)$/m)?.[1] ?? ''), mission: quote(item.match(/^    mission:\s*(.+)$/m)?.[1] ?? ''), focus: (item.match(/^    focus:\s*\[([^\]]*)\]/m)?.[1] ?? '').split(',').map(quote).filter(Boolean), risks, unknowns })).filter((charter) => charter.id && charter.mission);
}
function scopeItemFor(text: string, scopeItems: string[]): string | undefined {
  const synonyms: Record<string, string[]> = { detail: ['detail', 'detalle'], product: ['product', 'producto'], listing: ['listing', 'listado'], cart: ['cart', 'carrito'], remove: ['remove', 'eliminar'], price: ['price', 'precio'], name: ['name', 'nombre'], quantity: ['quantity', 'cantidad', 'indicador'] };
  const normalized = unaccent(text);
  if (/(name|nombre)/.test(normalized)) return scopeItems.find((item) => /nombre/.test(unaccent(item)));
  if (/(price|precio)/.test(normalized)) return scopeItems.find((item) => /precio/.test(unaccent(item)));
  if (/(return|regresar)/.test(normalized)) return scopeItems.find((item) => /regresar/.test(unaccent(item)));
  if (/(available|disponible|again|nuevamente)/.test(normalized)) return scopeItems.find((item) => /disponible|vuelva/.test(unaccent(item)));
  const concepts = Object.entries(synonyms).filter(([, words]) => words.some((word) => normalized.includes(word))).map(([concept]) => concept);
  return scopeItems.find((item) => { const candidate = unaccent(item); return concepts.some((concept) => synonyms[concept].some((word) => candidate.includes(word))); });
}

export function buildExplorationPlans(feature: string, discovery: string): { plans: ExplorationPlan[]; scopeItems: string[] } {
  const charters = chartersFrom(discovery); const scopeItems = listAfter(feature, 'include'); const relevantFeature = feature.split(/\n\s+exclude:/)[0]; const relevantDiscovery = discovery.split('out_of_scope:')[0]; const combined = `${relevantFeature}\n${scopeItems.join(' ')}\n${relevantDiscovery}`; const scope = (text: string): string | undefined => scopeItemFor(text, scopeItems);
  const action = (type: SemanticActionType, target: string, reason: string, save_as?: string): ExplorationPlanAction => ({ type, target, reason, save_as, scope_item: scope(reason) }); const actions: ExplorationPlanAction[] = [];
  if (has(combined, /authentic|autentic|login|sesion|usuario/)) actions.push(action('authenticate', 'application', 'The feature requires an authenticated user.'));
  const productContext = has(combined, /product|producto|listing|listado|catalog|catalogo/);
  if (productContext) { actions.push(action('observe_collection', 'product_listing', 'Observe the visible product listing.')); actions.push(action('select_visible_item', 'product', 'Select one visible product for the scenario.')); }
  if (has(combined, /detail|detalle/)) { actions.push(action('capture_value', 'visible_product.name', 'Capture the selected product name before navigation.', 'productName')); actions.push(action('capture_value', 'visible_product.price', 'Capture the selected product price before navigation.', 'productPrice')); actions.push(action('navigate_via_ui', 'selected_product.detail', 'Navigate through the visible product control to its detail.')); actions.push(action('inspect_state', 'product_detail', 'Inspect the observable product detail state.')); actions.push(action('compare_values', 'detail.product_name', 'Compare the detail product name with the captured listing name.')); actions.push(action('compare_values', 'detail.product_price', 'Compare the detail product price with the captured listing price.')); actions.push(action('go_back', 'product_listing', 'Return to the product listing through browser navigation.')); actions.push(action('inspect_state', 'product_listing', 'Confirm that the product listing is available again.')); }
  const cartContext = has(combined, /cart|carrito|remove|eliminar|badge|indicador de cantidad/);
  if (cartContext) { actions.push(action('add_selected_items', 'cart', 'Add the visible product selection described by the feature.')); if (has(combined, /second|segundo|different|diferente|both|ambos/)) actions.push(action('add_selected_items', 'cart', 'Add a second distinct visible product because the scenario requires it.')); actions.push(action('open_cart', 'cart', 'Open the visible cart entry.')); actions.push(action('capture_collection', 'cart', 'Inspect cart items and its visible quantity indicator.')); if (has(combined, /remove|eliminar/)) { actions.push(action('remove_item', 'cart', 'Remove one cart item to exercise the specified state transition.')); actions.push(action('capture_collection', 'cart', 'Inspect the remaining cart state after removal.')); if (has(combined, /empty|vacio|remaining|restante/)) { actions.push(action('remove_item', 'cart', 'Remove the remaining cart item because the boundary state is in scope.')); actions.push(action('capture_collection', 'cart', 'Inspect the empty cart boundary state.')); } } }
  if (cartContext) { const cartActions = actions.filter((item) => item.target === 'cart'); cartActions.forEach((item, index) => { item.scope_item = scopeItems[Math.min(index, scopeItems.length - 1)]; }); }
  const charter = charters[0] ?? { id: 'CHAR-001', mission: 'Explore the supplied feature.', focus: [], risks: ids(discovery, 'RSK'), unknowns: ids(discovery, 'UNK') }; return { scopeItems, plans: [{ charter_id: charter.id, focus: charter.mission, source_ids: [...charter.focus, ...charter.risks, ...charter.unknowns], actions }] };
}
function finding(feature: string, charter: Charter, id: string, title: string, expected: string, actual: string, evidence: string[], risk: string, scopeItems: string[], type: FindingType = 'observation'): ExploratoryFinding { return { id, feature, charter: charter.id, type, status: type === 'defect' || type === 'unexpected_behavior' ? 'potential_defect' : 'observation', title, description: actual, steps_to_reproduce: ['Execute the recorded exploratory plan for this charter.'], expected, actual, expected_or_reference: expected, observed_behavior: actual, risk, evidence, timestamp: new Date().toISOString(), traceability: { scenario_ids: charter.focus, risk_ids: charter.risks, unknown_ids: [], scope_items: scopeItems } }; }

export async function runExploratoryAgent(options: { featurePath: string; discoveryPath: string; testCasesPath?: string; outputDirectory: string }): Promise<ExplorationResult> {
  const started = new Date().toISOString(); const featureSpec = readFileSync(resolve(root, options.featurePath), 'utf8'); const discovery = readFileSync(resolve(root, options.discoveryPath), 'utf8'); if (options.testCasesPath) JSON.parse(readFileSync(resolve(root, options.testCasesPath), 'utf8'));
  const feature = yamlValue(featureSpec, 'name') || yamlValue(discovery, 'feature') || options.featurePath; const charters = chartersFrom(discovery); if (charters.length === 0) throw new Error('Discovery contains no actionable exploratory_charters.'); const { plans, scopeItems } = buildExplorationPlans(featureSpec, discovery); const charter = charters[0];
  const output = resolve(root, options.outputDirectory); mkdirSync(output, { recursive: true }); for (const file of readdirSync(output)) if (/^(EXP-.*\.json|exploration-session\.json|.*\.png)$/i.test(file)) unlinkSync(resolve(output, file));
  const actions: string[] = []; const evidence: string[] = []; const findings: ExploratoryFinding[] = []; const runtimeValues: Record<string, string> = {}; const unknowns = ids(discovery, 'UNK').map((id) => ({ id, status: 'unresolved' as const })); const coverage: CoverageItem[] = scopeItems.map((scope_item) => ({ scope_item, status: 'unexplored' })); const markCovered = (item?: string): void => { const match = coverage.find((entry) => entry.scope_item === item); if (match) match.status = 'covered'; };
  const browser = await chromium.launch({ headless: true }); const page = await browser.newPage(); const screenshot = async (name: string): Promise<string> => { const relative = `${options.outputDirectory}/${name}.png`; await page.screenshot({ path: resolve(root, relative), fullPage: true }); evidence.push(relative); return relative; }; const baseUrl = process.env.TEST_BASE_URL?.replace(/^['"]|['"]$/g, '') || 'https://www.saucedemo.com/'; const selected = (): ReturnType<Page['locator']> => page.locator('[data-test="inventory-item"]').first();
  const capture = async (target: string, saveAs?: string): Promise<string> => { let value = ''; if (target === 'visible_product.name') value = (await selected().locator('[data-test="inventory-item-name"]').innerText()).trim(); if (target === 'visible_product.price') value = (await selected().locator('[data-test="inventory-item-price"]').innerText()).trim(); if (target === 'detail.product_name') value = (await page.locator('[data-test="inventory-item-name"]').first().innerText()).trim(); if (target === 'detail.product_price') value = (await page.locator('[data-test="inventory-item-price"]').first().innerText()).trim(); if (saveAs) runtimeValues[saveAs] = value; actions.push(`capture ${target}${saveAs ? ` as ${saveAs}` : ''}: ${value}`); return value; };
  try {
    await page.goto(baseUrl); actions.push(`navigate ${baseUrl}`);
    for (const planAction of plans[0].actions) { const target = planAction.target ?? ''; markCovered(planAction.scope_item);
      if (planAction.type === 'authenticate') { await page.getByPlaceholder('Username').fill(process.env.TEST_STANDARD_USER_USERNAME || 'standard_user'); await page.getByPlaceholder('Password').fill(process.env.TEST_STANDARD_USER_PASSWORD || 'secret_sauce'); await page.getByRole('button', { name: 'Login' }).click(); await page.getByText('Products', { exact: true }).waitFor(); actions.push('authenticate through the visible login form'); }
      else if (planAction.type === 'observe_collection') { await page.getByText('Products', { exact: true }).waitFor(); actions.push('observe product listing'); await screenshot('01-product-listing'); }
      else if (planAction.type === 'select_visible_item') { const name = (await selected().locator('[data-test="inventory-item-name"]').innerText()).trim(); actions.push(`select visible product: ${name}`); }
      else if (planAction.type === 'capture_value') await capture(target, planAction.save_as);
      else if (planAction.type === 'navigate_via_ui') { await selected().locator('[data-test="inventory-item-name"]').click(); actions.push('navigate via visible product name to detail'); await screenshot('02-product-detail'); }
      else if (planAction.type === 'inspect_state') { await page.locator(target === 'product_detail' ? '[data-test="inventory-item-name"]' : '[data-test="inventory-list"]').first().waitFor(); actions.push(`inspect ${target} state`); }
      else if (planAction.type === 'compare_values') { const actualTarget = target.includes('name') ? 'detail.product_name' : 'detail.product_price'; const actual = await capture(actualTarget); const expected = target.includes('name') ? runtimeValues.productName : runtimeValues.productPrice; const equal = actual === expected; findings.push(finding(feature, charter, `EXP-${String(findings.length + 1).padStart(3, '0')}`, equal ? `The selected product detail preserved the product ${target.includes('name') ? 'name' : 'price'} observed in the listing.` : `The selected product detail changed the product ${target.includes('name') ? 'name' : 'price'}.`, `The detail ${target.includes('name') ? 'name' : 'price'} matches the listing value.`, `Listing value was ${expected}; detail value was ${actual}.`, evidence.slice(-1), 'Product information consistency', scopeItems, equal ? 'observation' : 'unexpected_behavior')); }
      else if (planAction.type === 'go_back') { await page.goBack(); await page.getByText('Products', { exact: true }).waitFor(); actions.push('return to product listing'); await screenshot('03-product-listing-returned'); findings.push(finding(feature, charter, `EXP-${String(findings.length + 1).padStart(3, '0')}`, 'Returning from product detail restored the product listing.', 'The product listing is displayed again.', `The product listing is visible at ${page.url()}.`, evidence.slice(-1), 'Navigation state transition', scopeItems)); }
      else if (planAction.type === 'add_selected_items') { const cards = page.locator('[data-test="inventory-item"]'); const index = actions.filter((entry) => entry.startsWith('add visible product')).length; const card = cards.nth(Math.min(index, await cards.count() - 1)); const name = (await card.locator('[data-test="inventory-item-name"]').innerText()).trim(); await card.getByRole('button', { name: 'Add to cart' }).click(); actions.push(`add visible product: ${name}`); }
      else if (planAction.type === 'open_cart') { await page.locator('[data-test="shopping-cart-link"]').click(); await page.locator('[data-test="cart-list"]').waitFor(); actions.push('open cart through visible cart link'); }
      else if (planAction.type === 'capture_collection') { const items = await page.locator('[data-test="inventory-item-name"]').allTextContents(); const badge = await page.locator('[data-test="shopping-cart-badge"]').count() ? await page.locator('[data-test="shopping-cart-badge"]').innerText() : '0'; const actual = `Visible cart items are ${items.map((item) => item.trim()).join(', ') || '(none)'} and the quantity indicator is ${badge}.`; actions.push(`inspect cart state: items=${items.map((item) => item.trim()).join(', ') || '(none)'}, badge=${badge}`); await screenshot(`cart-state-${findings.length + 1}`); const captureIndex = actions.filter((entry) => entry.startsWith('inspect cart state')).length; const expected = captureIndex === 1 ? 'The selected products are visible in the cart and the quantity indicator reflects both products.' : captureIndex === 2 ? 'After removing one product, the remaining product is visible and the quantity indicator is 1.' : 'After removing the remaining product, the cart is empty and the quantity indicator is 0.'; findings.push(finding(feature, charter, `EXP-${String(findings.length + 1).padStart(3, '0')}`, captureIndex === 1 ? 'Selected products are represented in the cart.' : captureIndex === 2 ? 'Removing one product preserves the remaining cart state.' : 'Removing the final product produces the empty cart boundary state.', expected, actual, evidence.slice(-1), 'Cart state transition and visible quantity consistency', scopeItems)); }
      else if (planAction.type === 'remove_item') { const remove = page.getByRole('button', { name: 'Remove' }); if (await remove.count()) { await remove.first().click(); actions.push('remove one visible cart item'); } else actions.push('remove item blocked: no Remove control is visible'); }
    }
    for (const item of coverage) if (item.status === 'unexplored') item.reason = 'No plan action was derived for this scope item.';
    const completed = new Date().toISOString(); const result: ExplorationResult = { exploratory_status: coverage.some((item) => item.status === 'unexplored') ? 'executed_with_gaps' : 'executed', feature, feature_path: options.featurePath, discovery_path: options.discoveryPath, charters, plans, charters_planned: charters.length, charters_executed: 1, charters_blocked: 0, findings_generated: findings.length, actions, evidence, runtime_values: runtimeValues, unknowns, coverage: { scope_items_explored: coverage.filter((item) => item.status === 'covered').length, scope_items_unexplored: coverage.filter((item) => item.status !== 'covered').length, items: coverage }, started_at: started, completed_at: completed };
    findings.forEach((item) => writeFileSync(resolve(output, `${item.id}.json`), `${JSON.stringify(item, null, 2)}\n`, 'utf8')); writeFileSync(resolve(output, 'exploration-session.json'), `${JSON.stringify(result, null, 2)}\n`, 'utf8'); return result;
  } finally { await browser.close(); }
}
